version: '3'
services:
  redis:
    container_name: broker
    image: 'redis'
    expose:
      - 6379
  app:
    container_name: app
    ## restart: always
    build: .
    ports:
      - '8080:8080'
      - '8081:8081'
    links:
      - redis
    env_file:
      - ~/.mvp.env